### ISSUE TITLE
Imported tasks not linked to the correct users.

### ISSUE THREAD

**Issue by cobuscoetsee** [mikerourke/toggl-to-clockify#7]
After importing it doesn't seem like it links entries to the correct users in the workspace. It only links all the entries to the account holder.

**Comment by mikerourke** [comment]
My bad, I forgot to accommodate for the Team/Users aspect of both tools (I was the only one using the tool). I'll work on it now. If I don't run into any major issues, I should be able to have the new version up tonight.

**Comment by mikerourke** [comment]
Alright so I think I got a little big for my britches. Correctly mapping the team <-> user group <-> project is going to require some time. I was planning on changing the structure from **by tool** (Toggl/Clockify) to **by entity** (Project, Client, Time Entry, etc.) eventually, but I might pull the trigger on that this week. I think adding the team and user group to the code as it is now may be too cumbersome. I'll keep you posted.

**Comment by cobuscoetsee** [comment]
Thanks looking forward to the update. :)

**Comment by cobuscoetsee** [comment]
Thanks looking forward to the update. :)

**Comment by mikerourke** [comment]
@cobuscoetsee I wanted to give an update on this. I've been swamped at work and haven't had a chance to dedicate too much time to this but I've been working on it when I can. It might be another week or so due to the holiday this weekend. I'll keep you posted.

**Comment by cobuscoetsee** [comment]
@mikerourke thanks so much. No rush, we decided only to start to use the tool 1 January 2019. :)

**Comment by igryski** [comment]
The transfer of all entries is indeed linked only to the account holder of the workspace. We are also looking forward to having this feature to work with our multiple-user database :+1:

**Comment by aleksandar-olic** [comment]
It looks like you're gonna need API token for each user if you want to create entries in their name. 

Maybe, for a start, transfer only one person's entries (the one doing the transfer). Then, each person can repeat the process and transfer their own entries. This way, a team can transfer all their data by running the importer multiple times and there's less development headaches

**Comment by mikerourke** [comment]
@malizmaj Good call, I was actually kicking around the idea of build a simple UI for it. It would make the configuration process easier and allow you to pick and choose the stuff you wanted to transfer. I'd like to accommodate for the users who aren't as technically inclined.

**Comment by igryski** [comment]
@malizmaj when transferring each person's entries separately, it seems the import from Toggl only pulls January entries now. Only this month appears in toggle.json, and in the created time entries in Clockify

**Comment by mikerourke** [comment]
@malizmaj @igryski FYI, I'm about 2 weeks away from a UI version of this tool that should address most of the issues you're having. You'll be able to select workspaces and years from what data is available and pick & chose projects, tags, etc. I'm going to host it on surge.sh or something along those lines. I'd like to add some tests and was hoping to get some logic in there to prevent duplicate time entries, but that's obviously a lot more complex.

The codebase is here: https://github.com/mikerourke/toggl-to-clockify-web. It's a looottt more code because it's a React/Redux app. PRs are welcome and I appreciate your patience.

**Comment by ethanclarke** [comment]
Any update on this? I just installed this importer this morning, put in my API tokens for my account as per the instructions and now have a giant jumble of entries in Clockify since it has all of the entries for 3 different staff people in 2018.

I guess I'll nuke the clockify account and start over but I can't even figure out how to run the user by user approach mentioned above.

**Comment by mikerourke** [comment]
@ethanclarke Managing multiple users might be tricky. I'm still hashing out how to accomplish that. I could probably add it to the web version I'm working on, but the order of operations would need to be very specific (i.e. before using the tool, setup workspaces with user email addresses that _exactly_ match Toggl, then perform a transfer). Testing it is going to be a little clunky and problematic, but I do want to add this feature in.

I've been trying to finish the damn thing but I've just been slammed at work. I have some time opening up the week after next. I have a list of people that I'll alert when I have something ready. I apologize for the delay and I'll let you know when it's good to go. Thanks!

**Comment by ethanclarke** [comment]
@mikerourke Have you had any time to work on this? I'd love to move my team to Clockify but we're stuck on Toggl for now! Even just a command line version of this would be fine. 
Thanks in advance!

**Comment by mikerourke** [comment]
@ethanclarke I apologize for the delayed response. Without getting into too much personal detail, I been in the process of selling my house for the past 2 weeks so my life has been complete bedlam. We’re closing tomorrow and my availability is about to skyrocket. I’ve been incredibly bothered by the fact that I haven’t been able to get this tool in a usable state despite my best efforts. I blew the dust off the web version last weekend and figured out what needs to be done. I’m planning on spending this weekend working on it. I appreciate your patience and I completely understand that it’s probably wearing thin. I would like to work with you on transferring team entries to ensure I have the workflow correct. I am committed to getting this thing up and running!

**Comment by ethanclarke** [comment]
Hi Mike,

No need to apologize! You are a volunteer, you have to fit this type of work around your life. 

The impatience I have is for Toggl who increased their prices such that a small business like mine struggle to afford them. But we can carry on for a month or two more. 

Good luck with the move!

**Comment by 908E** [comment]
Hello Mike,

I just wanted to say thanks for everything until now. I am in the same boat as Ethan as well. Toggl has been getting more and more expensive and I am looking for a change.

If you post a bitcoin / ETH address or paypal email I would be happy to send you an advance right away. I know that you are a volunteer and I know that your work is going to save a lot of people a lot of money. I'd be happy to pay for the privilege.  

As a minor suggestion, you may consider importing a Toggl CSV instead of using the API access. The Toggl CSV has all the data for all users (active and inactive) nicely organized and categorized. You can then use the Clockify API to export to Clockify. You may need to have API keys for each clockify user but that may not be a big deal.

Thanks again. Keep up the good work. Let me buy pizza and beers for the next couple weekends!

**Comment by mikerourke** [comment]
@908E That's very kind of you to offer, I propose you cover congratulatory pizza when the tool is up and running! With regard to the CSV thing, I have a few contentions:
- I don't think you can export to a CSV if you're on the free account, which would exclude a huge percentage of users.
- There's always some weird edge case or idiosyncrasy that needs to be accommodated for when importing/exporting files.
- At this point I'm so close to being done with the APIs that it makes more sense to continue on my current path.

I'll be working on the time entries/workflow stuff this week. I'll ping you and @ethanclarke when I have something to step through. I may just mock something up and have you go through the workflow (without actually transferring anything) just to make sure everything makes sense and functions correctly.  Thank you for being so accommodating, I appreciate it!

**Comment by 908E** [comment]
Thanks! Congratulatory pizza sounds like a good idea!

I thought that the CSVs would be a good way to work around the separate user issue but I agree that it may add some unnecessary complexity at this stage.
